404 page
Guitarninja1/erickaskim.com pull request #11
Opened 2021-08-16 18:10 UTC by Guitarninja1

<img width="375" alt="Screen Shot 2021-08-16 at 11 08 46 AM" src="https://user-images.githubusercontent.com/77123368/129609946-58609154-1b90-40d0-8a9a-23863d1350fc.png">
<img width="362" alt="Screen Shot 2021-08-16 at 11 08 25 AM" src="https://user-images.githubusercontent.com/77123368/129609954-1a8c2dc9-9874-4eaa-bf6a-1978fa8629df.png">

2021-08-16 18:15 UTC, kalm42 commented
You have conflicts to resolve. Your colors are off. The breadcrumbs are too wide. The spacing below 404 is too large.

2021-08-16 18:20 UTC, kalm42 requested changes

2021-08-16 18:20 UTC, kalm42 commented on pages/404.js
> +						<a className='fourzerofour--li-home'>Home</a>
Close but there's a more optimal solution. `fourzerofour--li fourzerfour--li__with-hyphen` feel free to rename that but you get the idea.

2021-08-16 18:20 UTC, kalm42 commented on pages/404.js
> +				</button>
Submit what form?

2021-08-16 18:20 UTC, kalm42 commented on styles/Global.css
> +	line-height: 160%;
Line height is commonly expressed in multiples. ie. `1.6` not `160%`

2021-08-16 18:20 UTC, kalm42 commented on styles/Global.css
> +	content: ' 	\2000\2001\2001 ─';
Why the spaces?

2021-08-16 19:52 UTC, Guitarninja1 commented
<img width="366" alt="Screen Shot 2021-08-16 at 12 50 34 PM" src="https://user-images.githubusercontent.com/77123368/129621554-2c795f6a-b4a4-4b30-817d-74839483fd46.png">
<img width="375" alt="Screen Shot 2021-08-16 at 11 08 46 AM" src="https://user-images.githubusercontent.com/77123368/129621563-07c2cb55-17bb-4a78-9d5e-0a949c9f5f96.png">

2021-08-16 21:57 UTC, Guitarninja1 commented
fix breadcrumbs commit 
<img width="360" alt="Mine" src="https://user-images.githubusercontent.com/77123368/129634446-2d6d36c8-01a6-4d40-a21f-7f6b5749d597.png">
<img width="375" alt="template" src="https://user-images.githubusercontent.com/77123368/129634448-ca9abc12-2731-4b2c-88c4-b42821f95d89.png">

2021-08-17 13:39 UTC, kalm42 approved these changes

2021-08-17 13:39 UTC, kalm42 commented on styles/Global.css
> +	left: calc(100vw - 85px);
Just putting this out there `right: 85px;`. Then there's a general rule that you always have at least two anchors. Top/left, bottom/right, ect. This isn't wrong. If you're having trouble positioning the hyphen remember to try setting the parent to `position: relative;`.

2021-08-17 13:39 UTC, kalm42 commented on styles/Global.css
> +	top: 34rem;
Here we do want pixel values.

2021-08-17 14:21 UTC, Guitarninja1 commented on styles/Global.css
> +	top: 34rem;
haaaaaattte

2021-08-17 14:29 UTC, kalm42 approved these changes

2021-08-17 14:30 UTC, merged