contact styling markI
Guitarninja1/erickaskim.com pull request #12
Opened 2021-08-17 21:08 UTC by Guitarninja1

<img width="374" alt="template contact" src="https://user-images.githubusercontent.com/77123368/129800888-7845961e-7381-41cb-ad26-d47af3343775.png">
<img width="376" alt="template message" src="https://user-images.githubusercontent.com/77123368/129800893-de8266a2-220c-46cf-89a4-4aa1fd016989.png">
<img width="374" alt="template intouch" src="https://user-images.githubusercontent.com/77123368/129800896-b27fd55a-3dee-43c4-a521-ed0720eb4da9.png">
<img width="345" alt="my message" src="https://user-images.githubusercontent.com/77123368/129800899-66ad3983-7a6c-499c-821a-4df9ccb91c5c.png">
<img width="343" alt="my connect" src="https://user-images.githubusercontent.com/77123368/129800900-01815bdd-190c-4e6c-8f3f-d5d6c16adc6b.png">
<img width="337" alt="my intouch" src="https://user-images.githubusercontent.com/77123368/129800901-7e487153-6084-4874-a9e7-72380f65a0f4.png">

2021-08-17 21:51 UTC, kalm42 commented
# Contact
Radial gradient
line height
font weight

# Send us a message
Description block
input padding
' *'
text area non-adjustable

# Always be in touch
linear gradient
title in all caps
left pad input
label 'I accept...'
left pad I accept
Terms should be link

2021-08-17 22:14 UTC, kalm42 submitted a review, later dismissed

2021-08-17 22:14 UTC, kalm42 commented on components/InTouch.js
> +					id='email'
You should be careful of generic ids.

2021-08-17 22:14 UTC, kalm42 commented on components/InTouch.js
> +					<label htmlFor='checkbox' className='sr-only' />
Your label has no content.

2021-08-17 22:14 UTC, kalm42 commented on components/InTouch.js
> +					<p className={styles.terms}>Terms and Conditions</p>
lol, that's fancy inline p tags. Don't do that. lol label > text / link

2021-08-17 22:14 UTC, kalm42 commented on components/Message.js
> +					id='email'
This 'id' conflicts with InTouch

2021-08-17 22:14 UTC, kalm42 commented on components/Message.module.css
> +	background-color: transparent;
Consider 'none'.

2021-08-17 22:14 UTC, kalm42 commented on views/contact.module.css
> +}
Empty

2021-08-17 22:14 UTC, kalm42 commented on views/contact.module.css
> +.phone,
Not needed with module find an abstract name that covers both.

2021-08-17 22:14 UTC, kalm42 commented on views/contact.module.css
> +.content1 {
Try for a more descriptive name.

2021-08-18 17:11 UTC, Guitarninja1 commented on components/Breadcrumbs.module.css
> +.list,
I had to separate them to do ::after on .home

2021-08-18 17:13 UTC, Guitarninja1 commented on components/Breadcrumbs.module.css
> +	margin: -15px 0 0 0;
I'm having trouble adjusting the offending element. Could use your help

2021-08-18 17:28 UTC, Guitarninja1 commented
<img width="374" alt="template contact" src="https://user-images.githubusercontent.com/77123368/129944525-ebb540a9-c049-4c41-9d4a-3e1595ca80ba.png">
<img width="376" alt="template message" src="https://user-images.githubusercontent.com/77123368/129944533-371bec6a-2824-4cf1-82cf-f969cf809d65.png">
<img width="374" alt="template intouch" src="https://user-images.githubusercontent.com/77123368/129944536-aeeb638b-9bea-4eea-8ec2-405fab1bc693.png">
<img width="343" alt="Screen Shot 2021-08-18 at 10 27 47 AM" src="https://user-images.githubusercontent.com/77123368/129944538-12f02aea-6bc1-4eed-8e95-de37e880e9ea.png">
<img width="343" alt="Screen Shot 2021-08-18 at 10 27 10 AM" src="https://user-images.githubusercontent.com/77123368/129944540-977bfb6e-4e17-430a-83bb-a21499d542d8.png">
<img width="339" alt="Screen Shot 2021-08-18 at 10 25 04 AM" src="https://user-images.githubusercontent.com/77123368/129944541-e5f64488-035d-423e-913a-3417ad30d308.png">

2021-08-18 18:54 UTC, Guitarninja1 commented
<img width="374" alt="template intouch" src="https://user-images.githubusercontent.com/77123368/129955782-63798c31-be0a-483f-a97d-c810b26cfc49.png">
<img width="343" alt="Screen Shot 2021-08-18 at 11 53 12 AM" src="https://user-images.githubusercontent.com/77123368/129955794-62282dca-c5a2-4928-a2ab-ad004ba1ae95.png">

2021-08-18 19:07 UTC, kalm42 requested changes

2021-08-18 19:07 UTC, kalm42 commented on components/Message.js
> +				<label htmlFor='name' className='sr-only'>
The htmlFor doesn't match the id of the input it's labeling.

2021-08-18 19:07 UTC, kalm42 commented on components/Message.js
> +				<label htmlFor='tel' className='sr-only'>
htmlfor

2021-08-18 19:07 UTC, kalm42 commented on components/Message.js
> +				<label htmlFor='email' className='sr-only'>
htmlfor

2021-08-18 19:07 UTC, kalm42 commented on components/Message.js
> +					type='message--email'
You updated the type not the. 'message--email' is not a valid input type.

2021-08-18 19:07 UTC, kalm42 commented on components/Message.js
> +				/>
Inputs need a label

2021-08-18 19:07 UTC, kalm42 commented on views/Contact.module.css
> +}
Empty

2021-08-18 20:38 UTC, kalm42 approved these changes

2021-08-18 20:38 UTC, kalm42 commented on components/InTouch.js
> +						<div className={styles.foo}>
I suggest changing this from a div to a p.

2021-08-18 20:38 UTC, kalm42 commented on components/InTouch.module.css
> +		inset 0px -15px 10px -12px rgba(0, 0, 0, 0.05);
Can you see this?

2021-08-18 20:38 UTC, kalm42 commented on components/InTouch.module.css
> +.foo {
Is there a better name?

2021-08-19 13:50 UTC, kalm42 approved these changes

2021-08-19 13:50 UTC, merged